### ISSUE TITLE
yarn install fails for api-client

### ISSUE THREAD

**Issue by damirn** [wireapp/wire-web-packages#152]
I'm trying to follow the guidelines for api-client, but I fail each time:

> api-client$ yarn install
yarn install v1.3.2
[1/4] Resolving packages...
success Already up-to-date.
$ yarn test
yarn run v1.3.2
$ yarn dist && yarn test:node && yarn test:browser
$ yarn clear && yarn build
$ rimraf dist
$ yarn build:node && yarn build:browser
$ tsc
src/main/Client.ts(32,28): error TS2307: Cannot find module '@wireapp/store-engine/dist/commonjs/engine'.
src/main/Config.ts(19,26): error TS2307: Cannot find module '@wireapp/store-engine/dist/commonjs/engine'.
src/main/auth/AccessTokenStore.ts(20,26): error TS2307: Cannot find module '@wireapp/store-engine/dist/commonjs/engine'.
src/main/auth/AccessTokenStore.ts(21,35): error TS2307: Cannot find module '@wireapp/store-engine/dist/commonjs/engine/error'.
src/main/auth/AccessTokenStore.ts(36,80): error TS7011: Function expression, which lacks return-type annotation, implicitly has an 'any' return type.
src/main/auth/AccessTokenStore.ts(52,14): error TS7011: Function expression, which lacks return-type annotation, implicitly has an 'any' return type.
src/main/auth/AuthAPI.ts(23,26): error TS2307: Cannot find module '@wireapp/store-engine/dist/commonjs/engine'.
src/main/http/HttpClient.ts(23,27): error TS2307: Cannot find module '@wireapp/queue-priority/dist/commonjs/PriorityQueue'.
src/main/shims/browser/cookie.ts(21,26): error TS2307: Cannot find module '@wireapp/store-engine/dist/commonjs/engine'.
src/main/shims/node/cookie.ts(22,26): error TS2307: Cannot find module '@wireapp/store-engine/dist/commonjs/engine'.
src/main/shims/node/cookie.ts(24,35): error TS2307: Cannot find module '@wireapp/store-engine/dist/commonjs/engine/error'.
src/main/shims/node/cookie.ts(31,12): error TS7006: Parameter 'error' implicitly has an 'any' type.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

I'm using node 6.11.5 on Ubuntu 16.04.

**Comment by bennyn** [comment]
Hi @damirn, you need to execute `yarn` on the top-level directory (which is `wire-web-packages`) and not on the `api-client` directory itself.

**Comment by bennyn** [comment]
@damirn: With `@wireapp/core` v0.0.22 do the following:

```bash
yarn add @wireapp/core
```

```typescript
const {Account} = require('@wireapp/core')
import {PayloadBundle} from '@wireapp/core/dist/commonjs/crypto/'
import {LoginData} from '@wireapp/api-client/dist/commonjs/auth/'

const account: Account = new Account()

const login: LoginData = {
  email: 'name@email.com',
  password: 'secret',
  persist: false
}

account.on(Account.INCOMING.TEXT_MESSAGE, (data: PayloadBundle) => {
  account.service.conversation.sendTextMessage(data.conversation, data.content)
})

account
.listen(login)
.catch((error: Error) => {
  console.error(error.stack)
  return process.exit(1)
})
```

**Comment by bennyn** [comment]
I will close this topic because it's **resolved**. Latest dev samples can be found here:
- https://github.com/wireapp/wire-web-packages/tree/master/packages/api-client#execution
- https://github.com/wireapp/wire-web-packages/tree/master/packages/core#example
