### ISSUE TITLE
cli-client install

### ISSUE THREAD

**Issue by pinoapino** [wireapp/wire-web-packages#428]
Please explain how to correctly set up cli-client on the latest Node docker image.
There are all kinds of errors.

**Comment by bennyn** [comment]
@pinoapino Which error do you see first? `PathValidationError`?

**Comment by pinoapino** [comment]
Yes. Something about path traversal and a PathValidationError.

**Comment by bennyn** [comment]
Ok! It will be fixed with this PR: https://github.com/wireapp/wire-web-packages/pull/466 😃

**Comment by bennyn** [comment]
@pinoapino The release which includes the fix to your issue is out. 🎉  

Please try again with "@wireapp/cli-client v1.3.53".
