### ISSUE TITLE
Integrate Storybook to showcase the components

### ISSUE THREAD

**Issue by lipis** [wireapp/wire-web-packages#51]
https://github.com/storybooks/storybook

**Comment by lipis** [comment]
We have a nice demo now.. so no need for that: https://wire-react-ui-kit.netlify.com/

**Comment by gregor** [comment]
@lipis Andy is actually working on it right now... Storybook provides so much more than our demo page.

**Comment by lipis** [comment]
Oups :)

**Comment by Yserz** [comment]
We have styleguidist now
